# roles/common/dotfiles.yml
---
- name: Ensure yadm is installed
  stat:
    path: "/usr/local/bin/yadm"
  register: yadm_installed

- name: Clone dotfiles using yadm
  tasks:
    - include_vars: vars/vault
    - command:
        cmd: yadm clone {{ dotfiles_repo_url }}
      when: yadm_installed.stat.exists == False
      become: no  # Run as user
