# roles/common/dotfiles.yml
---
- name: Ensure yadm is installed
  stat:
    path: "/usr/local/bin/yadm"
  register: yadm_installed

- name: Clone dotfiles using yadm
  command:
    cmd: "yadm clone {{ xyz }}"
  when: yadm_installed.stat.exists == False
  become: no  # Run as user
