# roles/common/ripgrep.yml
---
- name: Install ripgrep on Debian
  apt:
    name: ripgrep
    state: present
  when: ansible_os_family == 'Debian'

- name: Install ripgrep on macOS
  homebrew:
    name: ripgrep
    state: present
  when: ansible_os_family == 'Darwin'

- name: Install ripgrep on Arch
  pacman:
    name: ripgrep
    state: present
  when: ansible_os_family == 'Archlinux'
