# roles/common/rust.yml
---
- name: Download Rust installation script
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/install_rust.sh"
    mode: '0755'  # Setting execute permissions

- name: Install Rust
  command: "/tmp/install_rust.sh -y"
  args:
    creates: "/home/{{ lookup('env', 'USER') }}/.cargo/"

- name: Remove installation script
  file:
    path: "/tmp/install_rust.sh"
    state: absent
