# roles/common/terminal.yml
---
- name: Install Alacritty using cargo
  command: "/home/{{ lookup('env', 'USER') }}/.cargo/bin/cargo install alacritty"
  args:
    creates: "{{ lookup('env','HOME') }}/.cargo/bin/alacritty"
